### PR TITLE
Coherence Change Detection using Coherence in IfgramStack.h5

### PR DESCRIPTION
**Pull request by mgovorcin**

### CODE REVIEW

**Comment by mgovorcin** [comment]
<p>Applied all comments, thanks @yunjunz</p>

---

 <a href='https://app.reviewnb.com/insarlab/MintPy-tutorial/pull/37/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yunjunz** [comment]
Thank you @mgovorcin for addressing my previous comments. The notebook looks much simpler and cleaner now, which is very nice!

I added a few more minor suggestions on the newer version, which I hope you could address without much effort.

**Comment by yunjunz** [comment]
<p>I find the <code>methods</code> dict below unnecessary, could we use <code>methods = ['difference', 'histogram_matching', 'ratio']</code> instead? This values are exposed to the users, thus, I prefer them to be clear without ambiguity, even though it might be longer.</p><p> </p><pre class="ql-syntax" spellcheck="false">    # methods
&nbsp; &nbsp; methods = {
&nbsp; &nbsp; &nbsp; &nbsp; 'diff':'Difference',
&nbsp; &nbsp; &nbsp; &nbsp; 'hist':'Histogram Matching',
&nbsp; &nbsp; &nbsp; &nbsp; 'ratio':'Ratio',
&nbsp; &nbsp; }
</pre>

---

 <a href='https://app.reviewnb.com/insarlab/MintPy-tutorial/pull/37/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgovorcin** [comment]
<p>@yunjun I addressed all new comments, thank you for suggesting them as they improve the notebook greatly.</p><p> </p>

**Comment by mgovorcin** [comment]
<p>there should be a plot, as I did not remove plotting of initial results. It seems that ReviewNB failed to generate the plot. I noticed that it started acting weird after the third PR</p>

---

 <a href='https://app.reviewnb.com/insarlab/MintPy-tutorial/pull/37/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgovorcin** [comment]
<p>I believe Jupyter notebook plots this image as an output of save_kmz.py. I added the line "%matplotlib notebook" before this line in the new version to prevent plotting .kmz file.</p>

---

 <a href='https://app.reviewnb.com/insarlab/MintPy-tutorial/pull/37/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yunjunz** [comment]
<p>Right, the plot is shown in your forked repo: https://nbviewer.org/github/mgovorcin/MintPy-tutorial/blob/main/applications/coherence_change_detection.ipynb.</p>

---

 <a href='https://app.reviewnb.com/insarlab/MintPy-tutorial/pull/37/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by yunjunz — APPROVED** [review]
Looks great! Thank you @mgovorcin for this very cool notebook!

**Pull request merged**
