### PR TITLE
sbApp_hyp3: update url of the example dataset

### PR DESCRIPTION
**Pull request by cirrusasf**

### CODE REVIEW

**Comment by yunjunz** [comment]
Looks good. I like the new way of using `wget` to download rather than `aws`.

One details, I don't find the `prep_ts_hyp3` in the `hyp3-docs` repo currently. So I guess it's a planned future notebook there?

**Comment by yunjunz** [comment]
Hi @cirrusasf, I have tried your example dataset and everything seems to work out fine, which is great!

There are quite some redundant files in it, so I remove a lot of them, the remaining files are as below, which is ~1GB before compression and ~500 MB after compression into `RidgecrestSenDT71.tar.xz` file.  I would suggest uploading this to the AWS S3 bucket also for a smaller size on the user size.

With your permission, I would recommend letting me upload this to zenodo as well, where the other example datasets for mintpy sits. It would be similar to https://zenodo.org/record/3952950, where you and the related ASF team will be first author. 

What do you think?

```
(insar) yunjunz:~/data/test/RidgecrestSenDT71>$ tree
.
├── hyp3
│   ├── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262
│   │   ├── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262.README.md.txt
│   │   ├── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262.txt
│   │   ├── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262_corr_clip.tif
│   │   ├── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262_dem_clip.tif
│   │   ├── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262_lv_phi_clip.tif
│   │   ├── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262_lv_theta_clip.tif
│   │   ├── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262_unw_phase.png
│   │   ├── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262_unw_phase.png.aux.xml
│   │   ├── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262_unw_phase.png.xml
│   │   ├── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262_unw_phase_clip.tif
│   │   └── S1AA_20190610T135156_20190622T135157_VVP012_INT80_G_ueF_1262_water_mask_clip.tif
│   ├── S1AA_20190610T135156_20190704T135158_VVP024_INT80_G_ueF_612C
│   │   ├── S1AA_20190610T135156_20190704T135158_VVP024_INT80_G_ueF_612C.README.md.txt
│   │   ├── S1AA_20190610T135156_20190704T135158_VVP024_INT80_G_ueF_612C.txt
│   │   ├── S1AA_20190610T135156_20190704T135158_VVP024_INT80_G_ueF_612C_corr_clip.tif
│   │   ├── S1AA_20190610T135156_20190704T135158_VVP024_INT80_G_ueF_612C_unw_phase.png
│   │   ├── S1AA_20190610T135156_20190704T135158_VVP024_INT80_G_ueF_612C_unw_phase.png.aux.xml
│   │   ├── S1AA_20190610T135156_20190704T135158_VVP024_INT80_G_ueF_612C_unw_phase.png.xml
│   │   └── S1AA_20190610T135156_20190704T135158_VVP024_INT80_G_ueF_612C_unw_phase_clip.tif
│   ├── S1AA_20190622T135157_20190704T135158_VVP012_INT80_G_ueF_4C43
│   │   ├── S1AA_20190622T135157_20190704T135158_VVP012_INT80_G_ueF_4C43.README.md.txt
│   │   ├── S1AA_20190622T135157_20190704T135158_VVP012_INT80_G_ueF_4C43.txt
│   │   ├── S1AA_20190622T135157_20190704T135158_VVP012_INT80_G_ueF_4C43_corr_clip.tif
│   │   ├── S1AA_20190622T135157_20190704T135158_VVP012_INT80_G_ueF_4C43_unw_phase.png
│   │   ├── S1AA_20190622T135157_20190704T135158_VVP012_INT80_G_ueF_4C43_unw_phase.png.aux.xml
│   │   ├── S1AA_20190622T135157_20190704T135158_VVP012_INT80_G_ueF_4C43_unw_phase.png.xml
│   │   └── S1AA_20190622T135157_20190704T135158_VVP012_INT80_G_ueF_4C43_unw_phase_clip.tif
│   ├── S1AA_20190622T135157_20190716T135159_VVP024_INT80_G_ueF_BA28
│   │   ├── S1AA_20190622T135157_20190716T135159_VVP024_INT80_G_ueF_BA28.README.md.txt
│   │   ├── S1AA_20190622T135157_20190716T135159_VVP024_INT80_G_ueF_BA28.txt
│   │   ├── S1AA_20190622T135157_20190716T135159_VVP024_INT80_G_ueF_BA28_corr_clip.tif
│   │   ├── S1AA_20190622T135157_20190716T135159_VVP024_INT80_G_ueF_BA28_unw_phase.png
│   │   ├── S1AA_20190622T135157_20190716T135159_VVP024_INT80_G_ueF_BA28_unw_phase.png.aux.xml
│   │   ├── S1AA_20190622T135157_20190716T135159_VVP024_INT80_G_ueF_BA28_unw_phase.png.xml
│   │   └── S1AA_20190622T135157_20190716T135159_VVP024_INT80_G_ueF_BA28_unw_phase_clip.tif
│   ├── S1AA_20190704T135158_20190716T135159_VVP012_INT80_G_ueF_EF5F
│   │   ├── S1AA_20190704T135158_20190716T135159_VVP012_INT80_G_ueF_EF5F.README.md.txt
│   │   ├── S1AA_20190704T135158_20190716T135159_VVP012_INT80_G_ueF_EF5F.txt
│   │   ├── S1AA_20190704T135158_20190716T135159_VVP012_INT80_G_ueF_EF5F_corr_clip.tif
│   │   ├── S1AA_20190704T135158_20190716T135159_VVP012_INT80_G_ueF_EF5F_unw_phase.png
│   │   ├── S1AA_20190704T135158_20190716T135159_VVP012_INT80_G_ueF_EF5F_unw_phase.png.aux.xml
│   │   ├── S1AA_20190704T135158_20190716T135159_VVP012_INT80_G_ueF_EF5F_unw_phase.png.xml
│   │   └── S1AA_20190704T135158_20190716T135159_VVP012_INT80_G_ueF_EF5F_unw_phase_clip.tif
│   ├── S1AA_20190704T135158_20190728T135159_VVP024_INT80_G_ueF_513C
│   │   ├── S1AA_20190704T135158_20190728T135159_VVP024_INT80_G_ueF_513C.README.md.txt
│   │   ├── S1AA_20190704T135158_20190728T135159_VVP024_INT80_G_ueF_513C.txt
│   │   ├── S1AA_20190704T135158_20190728T135159_VVP024_INT80_G_ueF_513C_corr_clip.tif
│   │   ├── S1AA_20190704T135158_20190728T135159_VVP024_INT80_G_ueF_513C_unw_phase.png
│   │   ├── S1AA_20190704T135158_20190728T135159_VVP024_INT80_G_ueF_513C_unw_phase.png.aux.xml
│   │   ├── S1AA_20190704T135158_20190728T135159_VVP024_INT80_G_ueF_513C_unw_phase.png.xml
│   │   └── S1AA_20190704T135158_20190728T135159_VVP024_INT80_G_ueF_513C_unw_phase_clip.tif
│   ├── S1AA_20190716T135159_20190728T135159_VVP012_INT80_G_ueF_3927
│   │   ├── S1AA_20190716T135159_20190728T135159_VVP012_INT80_G_ueF_3927.README.md.txt
│   │   ├── S1AA_20190716T135159_20190728T135159_VVP012_INT80_G_ueF_3927.txt
│   │   ├── S1AA_20190716T135159_20190728T135159_VVP012_INT80_G_ueF_3927_corr_clip.tif
│   │   ├── S1AA_20190716T135159_20190728T135159_VVP012_INT80_G_ueF_3927_unw_phase.png
│   │   ├── S1AA_20190716T135159_20190728T135159_VVP012_INT80_G_ueF_3927_unw_phase.png.aux.xml
│   │   ├── S1AA_20190716T135159_20190728T135159_VVP012_INT80_G_ueF_3927_unw_phase.png.xml
│   │   └── S1AA_20190716T135159_20190728T135159_VVP012_INT80_G_ueF_3927_unw_phase_clip.tif
│   ├── S1AA_20190716T135159_20190809T135200_VVP024_INT80_G_ueF_9D01
│   │   ├── S1AA_20190716T135159_20190809T135200_VVP024_INT80_G_ueF_9D01.README.md.txt
│   │   ├── S1AA_20190716T135159_20190809T135200_VVP024_INT80_G_ueF_9D01.txt
│   │   ├── S1AA_20190716T135159_20190809T135200_VVP024_INT80_G_ueF_9D01_corr_clip.tif
│   │   ├── S1AA_20190716T135159_20190809T135200_VVP024_INT80_G_ueF_9D01_unw_phase.png
│   │   ├── S1AA_20190716T135159_20190809T135200_VVP024_INT80_G_ueF_9D01_unw_phase.png.aux.xml
│   │   ├── S1AA_20190716T135159_20190809T135200_VVP024_INT80_G_ueF_9D01_unw_phase.png.xml
│   │   └── S1AA_20190716T135159_20190809T135200_VVP024_INT80_G_ueF_9D01_unw_phase_clip.tif
│   ├── S1AA_20190728T135159_20190809T135200_VVP012_INT80_G_ueF_C175
│   │   ├── S1AA_20190728T135159_20190809T135200_VVP012_INT80_G_ueF_C175.README.md.txt
│   │   ├── S1AA_20190728T135159_20190809T135200_VVP012_INT80_G_ueF_C175.txt
│   │   ├── S1AA_20190728T135159_20190809T135200_VVP012_INT80_G_ueF_C175_corr_clip.tif
│   │   ├── S1AA_20190728T135159_20190809T135200_VVP012_INT80_G_ueF_C175_unw_phase.png
│   │   ├── S1AA_20190728T135159_20190809T135200_VVP012_INT80_G_ueF_C175_unw_phase.png.aux.xml
│   │   ├── S1AA_20190728T135159_20190809T135200_VVP012_INT80_G_ueF_C175_unw_phase.png.xml
│   │   └── S1AA_20190728T135159_20190809T135200_VVP012_INT80_G_ueF_C175_unw_phase_clip.tif
│   ├── S1AA_20190728T135159_20190821T135201_VVP024_INT80_G_ueF_1D6B
│   │   ├── S1AA_20190728T135159_20190821T135201_VVP024_INT80_G_ueF_1D6B.README.md.txt
│   │   ├── S1AA_20190728T135159_20190821T135201_VVP024_INT80_G_ueF_1D6B.txt
│   │   ├── S1AA_20190728T135159_20190821T135201_VVP024_INT80_G_ueF_1D6B_corr_clip.tif
│   │   ├── S1AA_20190728T135159_20190821T135201_VVP024_INT80_G_ueF_1D6B_unw_phase.png
│   │   ├── S1AA_20190728T135159_20190821T135201_VVP024_INT80_G_ueF_1D6B_unw_phase.png.aux.xml
│   │   ├── S1AA_20190728T135159_20190821T135201_VVP024_INT80_G_ueF_1D6B_unw_phase.png.xml
│   │   └── S1AA_20190728T135159_20190821T135201_VVP024_INT80_G_ueF_1D6B_unw_phase_clip.tif
│   └── S1AA_20190809T135200_20190821T135201_VVP012_INT80_G_ueF_FA04
│       ├── S1AA_20190809T135200_20190821T135201_VVP012_INT80_G_ueF_FA04.README.md.txt
│       ├── S1AA_20190809T135200_20190821T135201_VVP012_INT80_G_ueF_FA04.txt
│       ├── S1AA_20190809T135200_20190821T135201_VVP012_INT80_G_ueF_FA04_corr_clip.tif
│       ├── S1AA_20190809T135200_20190821T135201_VVP012_INT80_G_ueF_FA04_unw_phase.png
│       ├── S1AA_20190809T135200_20190821T135201_VVP012_INT80_G_ueF_FA04_unw_phase.png.aux.xml
│       ├── S1AA_20190809T135200_20190821T135201_VVP012_INT80_G_ueF_FA04_unw_phase.png.xml
│       └── S1AA_20190809T135200_20190821T135201_VVP012_INT80_G_ueF_FA04_unw_phase_clip.tif
└── mintpy
    └── RidgecrestSenDT71.txt

13 directories, 82 files
```

**Comment by cirrusasf** [comment]
Hi Yunjun,

Go ahead to upload the example dataset to the zenodo website.

Thank you,

Jiang

**Comment by yunjunz** [comment]
Great. Could you provide a list of names and affiliations to be added to the authors list of the dataset on Zenodo?

**Comment by cirrusasf** [comment]
Hi Yunjun,

The list of the authors:

Jiang Zhu, Andrew Johnston, Joseph Kennedy, Heidi Kristenson, Thomas Logan,
James Rine, Rebecca Miller, and Bill Hauer

Alaska Satellite Facility (ASF), University of Alaska Fairbanks,

(email: ***@***.***)

Thank you!

Jiang


The new dataset are here:
https://jzhu-hyp3-dev.s3.us-west-2.amazonaws.com/hyp3-mintpy-example/Ridgecrest.zip

**Comment by yunjunz** [comment]
Thanks for the list. I will let you know when it's uploaded and available on Zenodo.

**Comment by yunjunz** [comment]
Hi @cirrusasf, the dataset is now on zenodo: https://zenodo.org/record/5502403. Cheers.

**Review by yunjunz — APPROVED** [review]

**Pull request merged**
