### PR TITLE
coherence change detection: bugfix + folium plot

### PR DESCRIPTION
**Pull request by mgovorcin**
- fix few bugs in plotting function plot_ccd
 - replaced ax.invert with mintpy.utils.plot.auto_flip_direction

### CODE REVIEW

**Comment by yunjunz** [comment]
Thank you @mgovorcin. Looks great overall. I only have a few minor suggestions on details.

**Comment by mgovorcin** [comment]
<p>applied</p>

---

 <a href='https://app.reviewnb.com/insarlab/MintPy-tutorial/pull/49/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgovorcin** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/insarlab/MintPy-tutorial/pull/49/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mgovorcin** [comment]
<p>applied</p>

---

 <a href='https://app.reviewnb.com/insarlab/MintPy-tutorial/pull/49/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yunjunz** [comment]
Thanks @mgovorcin. One last thing: The google earth screen shot is very intuitive. I would highly recommend keeping it.

```python
from IPython.display import Image
Image("Fernandina_eruptionSep2017.png")
```

**Review by yunjunz — APPROVED** [review]
Thank you @mgovorcin. The folium plot is beautiful! Looks all good to me, squash and merge whenever you are ready please.

**Pull request merged**
